[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/meet"
  to = "https://vyte.in/NdagiStanley"
  status = 301
  force = true
