[build]
  publish = "public"
  command = "yarn build"
[build.environment]
  YARN_VERSION = "1.3.2"
  YARN_FLAGS = "--no-ignore-optional"

[[redirects]]
  from = "/me"
  to = "https://bit.ly/about-stanmd"
  status = 301
  force = true

[[redirects]]
  from = "/chat"
  to = "https://bit.ly/linktree-stan"
  status = 301
  force = true

[[redirects]]
  from = "/devstory"
  to = "https://bit.ly/md-devstory"
  status = 301
  force = true

[[redirects]]
  from = "/meet"
  to = "https://bit.ly/meet-md"
  status = 301
  force = true

[[redirects]]
  from = "/learn/math"
  to = "https://bit.ly/MD-math"
  status = 301
  force = true

[[redirects]]
  from = "/kingdombiz"
  to = "https://bit.ly/KB-home"
  status = 301
  force = true

[[redirects]]
  from = "/kingdombiz/tech"
  to = "https://bit.ly/KB-with-tech"
  status = 301
  force = true

[[redirects]]
  from = "/kingdombiz/lens"
  to = "https://bit.ly/KB-bible-lens"
  status = 301
  force = true

[[redirects]]
  from = "/kingdombiz/gallery"
  to = "https://bit.ly/KB-gallery"
  status = 301
  force = true
